global_costmap:
  global_costmap:
    ros__parameters:
      publish_frequency: 1.0
      robot_base_frame: base_link
      track_unknown_space: true
      robot_radius: 0.22
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
planner_server:
  ros__parameters:
    GridBased:
      plugin: nav2_navfn_planner::NavfnPlanner
      tolerance: 0.5
      allow_unknown: true
