global_costmap:
  global_costmap:
    ros__parameters:
      plugins: [static_layer, inflation_layer]
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        cost_scaling_factor: 3.0
        inflation_radius: 0.22
